<a href="https://colab.research.google.com/github/jyotinayak321/IBM-ML-Training/blob/main/FEATURE_CONSTRUCTION_AND_FEATURES_SPLITTING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Feacture Construction** is the process of manually creating new features from existing features by combining, transforming or deriving them based on domain knowledge and intuition.

In [2]:
import pandas as pd
df = pd.read_csv("weight-height (1).csv")

In [4]:
# New features
df['Height_m'] = df['Height'] * 0.0254
df['Weight_kg'] = df['Weight'] * 0.453592

df.head()

  Gender     Height      Weight  Height_m   Weight_kg
0   Male  73.847017  241.893563  1.875714  109.720985
1   Male  68.781904  162.310473  1.747060   73.622732
2   Male  74.110105  212.740856  1.882397   96.497550
3   Male  71.730978  220.042470  1.821967   99.809504
4   Male  69.881796  206.349801  1.774998   93.598619

In [5]:
df['BMI'] = df['Weight_kg'] / (df['Height_m'] ** 2)

df.head()

  Gender     Height      Weight  Height_m   Weight_kg        BMI
0   Male  73.847017  241.893563  1.875714  109.720985  31.185761
1   Male  68.781904  162.310473  1.747060   73.622732  24.121044
2   Male  74.110105  212.740856  1.882397   96.497550  27.232906
3   Male  71.730978  220.042470  1.821967   99.809504  30.067059
4   Male  69.881796  206.349801  1.774998   93.598619  29.708033

In [6]:
def bmi_category(bmi):
    if bmi < 18.5:
        return 'Underweight'
    elif bmi < 25:
        return 'Normal'
    elif bmi < 30:
        return 'Overweight'
    else:
        return 'Obese'

df['BMI_Category'] = df['BMI'].apply(bmi_category)

df.head()

  Gender     Height      Weight  Height_m   Weight_kg        BMI BMI_Category
0   Male  73.847017  241.893563  1.875714  109.720985  31.185761        Obese
1   Male  68.781904  162.310473  1.747060   73.622732  24.121044       Normal
2   Male  74.110105  212.740856  1.882397   96.497550  27.232906   Overweight
3   Male  71.730978  220.042470  1.821967   99.809504  30.067059        Obese
4   Male  69.881796  206.349801  1.774998   93.598619  29.708033   Overweight

**Feature Splitting ** is the process of breaking down a single columns that contain multiple pieces of information into separate ,atomic columns.this adresses non tidy data where multiple value are stored in a single cell.

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[['Height_scaled', 'Weight_scaled']] = scaler.fit_transform(
    df[['Height', 'Weight']]
)

df.head()

,Gender,Height,Weight,Height_m,Weight_kg,BMI,BMI_Category,Height_scaled,Weight_scaled
0,Male,73.847017,241.893563,1.875714,109.720985,31.185761,Obese,1.944061,2.505797
1,Male,68.781904,162.310473,1.747060,73.622732,24.121044,Normal,0.627537,0.027101
2,Male,74.110105,212.740856,1.882397,96.497550,27.232906,Overweight,2.012443,1.597806
3,Male,71.730978,220.042470,1.821967,99.809504,30.067059,Obese,1.394060,1.825222
4,Male,69.881796,206.349801,1.774998,93.598619,29.708033,Overweight,0.913421,1.398750

In [8]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[['Height_scaled', 'Weight_scaled']] = scaler.fit_transform(
    df[['Height', 'Weight']]
)

df.head()

,Gender,Height,Weight,Height_m,Weight_kg,BMI,BMI_Category,Height_scaled,Weight_scaled
0,Male,73.847017,241.893563,1.875714,109.720985,31.185761,Obese,0.791728,0.863139
1,Male,68.781904,162.310473,1.747060,73.622732,24.121044,Normal,0.586958,0.475476
2,Male,74.110105,212.740856,1.882397,96.497550,27.232906,Overweight,0.802364,0.721131
3,Male,71.730978,220.042470,1.821967,99.809504,30.067059,Obese,0.706182,0.756699
4,Male,69.881796,206.349801,1.774998,93.598619,29.708033,Overweight,0.631424,0.689999

Feature Scaling is a preprocessing technique used to bring numerical features to a similar scale so that features with larger numerical values do not dominate the model. Common techniques are Standardization and Min-Max Normalization.