<a href="https://colab.research.google.com/github/jyotinayak321/IBM-training_-learning-/blob/main/practice_question_on_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Easy Level (1–10) ***

In [ ]:
#import pandas library


import pandas as pd
import numpy as np

In [33]:
#read a csv file name employee
df = pd.read_csv('employee_data.csv')

In [34]:
#Display the first 10 rows
df.head(10)

,Index,Employee_ID,Age,Department,Is_Manager,Join_Date,Experience,Salary
0,0,8794,60,Finance,False,1994-03-24,30,238668
1,1,8222,28,Sales,True,1979-12-08,13,105995
2,2,7643,30,Marketing,False,1998-09-25,11,96120
3,3,2737,38,HR,True,2011-11-23,20,153525
4,4,8557,61,HR,True,1976-10-08,31,249192
5,5,8484,31,Marketing,False,1982-06-07,14,112443
6,6,5854,64,Finance,False,1981-11-12,33,269150
7,7,6012,33,Finance,False,1983-09-28,13,99541
8,8,7462,34,Finance,False,2021-01-22,15,119128
9,9,7276,23,Finance,False,2014-10-03,11,83249

# Display information about the DataFrame (data types and non-null values)
df.info()

In [36]:
 # Display the last 5 rows of the DataFrame
 df.tail(5)

,Index,Employee_ID,Age,Department,Is_Manager,Join_Date,Experience,Salary
495,495,8426,32,Marketing,True,2013-12-04,16,126088
496,496,9810,26,IT,True,2022-05-02,15,118094
497,497,5396,34,Finance,False,2025-04-22,16,131208
498,498,7546,60,HR,False,1970-01-13,28,224502
499,499,7744,29,Finance,True,1988-06-21,15,114758

In [38]:
#  Display the names of all columns.
df.columns

Index(['Index', 'Employee_ID', 'Age', 'Department', 'Is_Manager', 'Join_Date',
       'Experience', 'Salary'],
      dtype='object')

In [47]:
# Find the total number of missing values in each column.
df.isnull().sum()

Index          0
Employee_ID    0
Age            0
Department     0
Is_Manager     0
Join_Date      0
Experience     0
Salary         0
dtype: int64

In [48]:
# if we want missing value of all colm
df.isnull()

,Index,Employee_ID,Age,Department,Is_Manager,Join_Date,Experience,Salary
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False

In [55]:
#Select only the Name(name is not in index so I choose employee_Id) and Salary columns
df[['Employee_ID', 'Salary']]

     Employee_ID  Salary
0           8794  238668
1           8222  105995
2           7643   96120
3           2737  153525
4           8557  249192
..           ...     ...
495         8426  126088
496         9810  118094
497         5396  131208
498         7546  224502
499         7744  114758

[500 rows x 2 columns]

In [57]:
# Display all employees whose Age is greater than 30
df[df["Age"] > 30]

,Index,Employee_ID,Age,Department,Is_Manager,Join_Date,Experience,Salary
0,0,8794,60,Finance,False,1994-03-24,30,238668
3,3,2737,38,HR,True,2011-11-23,20,153525
4,4,8557,61,HR,True,1976-10-08,31,249192
5,5,8484,31,Marketing,False,1982-06-07,14,112443
6,6,5854,64,Finance,False,1981-11-12,33,269150
...,...,...,...,...,...,...,...,...
493,493,3870,42,IT,False,1973-01-17,22,176978
494,494,3740,59,HR,False,2014-05-30,31,257256
495,495,8426,32,Marketing,True,2013-12-04,16,126088
497,497,5396,34,Finance,False,2025-04-22,16,131208
498,498,7546,60,HR,False,1970-01-13,28,224502

In [61]:
# Some comdition practice question

# if  want "HR" and "Finance" at the same time
df[(df["Department"] == "HR") & (df["Department"] == "Finance")]

Empty DataFrame
Columns: [Index, Employee_ID, Age, Department, Is_Manager, Join_Date, Experience, Salary]
Index: []

In [63]:
#if i want semoultaneously any condition
df[(df["Department"] == "HR") | (df["Department"] == "Finance")]

,Index,Employee_ID,Age,Department,Is_Manager,Join_Date,Experience,Salary
0,0,8794,60,Finance,False,1994-03-24,30,238668
3,3,2737,38,HR,True,2011-11-23,20,153525
4,4,8557,61,HR,True,1976-10-08,31,249192
6,6,5854,64,Finance,False,1981-11-12,33,269150
7,7,6012,33,Finance,False,1983-09-28,13,99541
...,...,...,...,...,...,...,...,...
492,492,6309,43,HR,True,1993-10-24,23,183906
494,494,3740,59,HR,False,2014-05-30,31,257256
497,497,5396,34,Finance,False,2025-04-22,16,131208
498,498,7546,60,HR,False,1970-01-13,28,224502
499,499,7744,29,Finance,True,1988-06-21,15,114758

# ***Moderate Level (11–20) ***

In [64]:
#Display employees whose Department is "IT"
df[df["Department"] == "IT"]

,Index,Employee_ID,Age,Department,Is_Manager,Join_Date,Experience,Salary
10,10,6621,51,IT,True,1974-03-12,26,201259
11,11,7461,43,IT,True,1991-06-08,17,144477
16,16,9901,60,IT,True,2001-03-22,27,209673
19,19,4049,45,IT,True,1992-10-09,24,193695
24,24,2444,43,IT,True,1985-02-13,22,181254
...,...,...,...,...,...,...,...,...
481,481,5168,23,IT,True,1973-03-27,10,85536
488,488,5175,64,IT,False,2001-10-01,35,285886
489,489,8349,48,IT,True,1974-05-27,23,177664
493,493,3870,42,IT,False,1973-01-17,22,176978
496,496,9810,26,IT,True,2022-05-02,15,118094

In [65]:
#Display employees whose Salary is between 40,000 and 80,000
df[(df["Salary"] >= 40000) & (df["Salary"] <= 80000)]

,Index,Employee_ID,Age,Department,Is_Manager,Join_Date,Experience,Salary
148,148,2759,24,IT,False,2017-12-13,9,78650
186,186,7336,22,Sales,True,1995-04-25,8,57732
266,266,2461,29,HR,True,2015-07-19,10,76240
271,271,3881,23,IT,True,1972-02-07,9,67144
324,324,9164,25,Finance,False,2019-07-26,9,75895
356,356,1541,27,IT,True,1986-10-11,11,78632
359,359,8399,24,HR,True,2012-08-29,9,69736
374,374,6914,23,Sales,False,2010-03-07,9,66124
379,379,2974,22,Sales,False,2020-06-29,7,43177
390,390,6190,23,IT,True,2016-05-16,10,75579
405,405,9975,22,IT,True,2004-05-16,9,65079
417,417,9276,23,IT,False,1983-03-08,10,75749
446,446,2639,24,HR,False,1997-01-23,10,75812
447,447,3328,24,Sales,True,1987-09-01,8,68134
469,469,1919,23,HR,True,1985-09-08,10,78834

In [66]:
#Add a new column Bonus equal to 15% of Salary
df["Bonus"] = df["Salary"] * 0.17

In [67]:
# Bonus colm is created let's have a look
df

,Index,Employee_ID,Age,Department,Is_Manager,Join_Date,Experience,Salary,Bonus
0,0,8794,60,Finance,False,1994-03-24,30,238668,40573.56
1,1,8222,28,Sales,True,1979-12-08,13,105995,18019.15
2,2,7643,30,Marketing,False,1998-09-25,11,96120,16340.40
3,3,2737,38,HR,True,2011-11-23,20,153525,26099.25
4,4,8557,61,HR,True,1976-10-08,31,249192,42362.64
...,...,...,...,...,...,...,...,...,...
495,495,8426,32,Marketing,True,2013-12-04,16,126088,21434.96
496,496,9810,26,IT,True,2022-05-02,15,118094,20075.98
497,497,5396,34,Finance,False,2025-04-22,16,131208,22305.36
498,498,7546,60,HR,False,1970-01-13,28,224502,38165.34
499,499,7744,29,Finance,True,1988-06-21,15,114758,19508.86

In [68]:
#Rename the column Dept to Department

df.rename(columns={"Join_Date": "Joining_Date"}, inplace=True)

In [69]:
# Now lets have a look ,i sthe rename is applied aur not
df

,Index,Employee_ID,Age,Department,Is_Manager,Joining_Date,Experience,Salary,Bonus
0,0,8794,60,Finance,False,1994-03-24,30,238668,40573.56
1,1,8222,28,Sales,True,1979-12-08,13,105995,18019.15
2,2,7643,30,Marketing,False,1998-09-25,11,96120,16340.40
3,3,2737,38,HR,True,2011-11-23,20,153525,26099.25
4,4,8557,61,HR,True,1976-10-08,31,249192,42362.64
...,...,...,...,...,...,...,...,...,...
495,495,8426,32,Marketing,True,2013-12-04,16,126088,21434.96
496,496,9810,26,IT,True,2022-05-02,15,118094,20075.98
497,497,5396,34,Finance,False,2025-04-22,16,131208,22305.36
498,498,7546,60,HR,False,1970-01-13,28,224502,38165.34
499,499,7744,29,Finance,True,1988-06-21,15,114758,19508.86

In [70]:
#Delete the Index column
df.drop("Index", axis=1, inplace=True)

"Address" → Column name to remove.

axis=1 → Specifies that you're deleting a column (axis=0 is for rows).

inplace=True → Modifies the original DataFrame

In [73]:
df # now there will be no index colm any more

,Employee_ID,Age,Department,Is_Manager,Joining_Date,Experience,Salary,Bonus
0,8794,60,Finance,False,1994-03-24,30,238668,40573.56
1,8222,28,Sales,True,1979-12-08,13,105995,18019.15
2,7643,30,Marketing,False,1998-09-25,11,96120,16340.40
3,2737,38,HR,True,2011-11-23,20,153525,26099.25
4,8557,61,HR,True,1976-10-08,31,249192,42362.64
...,...,...,...,...,...,...,...,...
495,8426,32,Marketing,True,2013-12-04,16,126088,21434.96
496,9810,26,IT,True,2022-05-02,15,118094,20075.98
497,5396,34,Finance,False,2025-04-22,16,131208,22305.36
498,7546,60,HR,False,1970-01-13,28,224502,38165.34
499,7744,29,Finance,True,1988-06-21,15,114758,19508.86

In [74]:
#Count the number of employees in each department

#Best when you only need the frequency of values in one column.

print(df["Department"].value_counts())

Department
IT           110
Sales        106
Finance      102
Marketing     95
HR            87
Name: count, dtype: int64

In [80]:
# groupby().size() → Better when you're already using groupby() or need more complex grouped calculations.
print(df.groupby("Department").size().reset_index(name="Employee_Count"))

  Department  Employee_Count
0    Finance             102
1         HR              87
2         IT             110
3  Marketing              95
4      Sales             106

In [82]:
# Find the average salary of each department using groupby()
print(df.groupby("Department")["Salary"].mean())


#reset_index() is used to convert the index back into a normal column and create a new default index

  Department  Average_Salary
0    Finance   167374.460784
1         HR   172150.574713
2         IT   172650.854545
3  Marketing   177127.200000
4      Sales   164615.216981

In [89]:
#Without reset index

print(df.groupby("Department")["Salary"].mean())

Department
Finance      167374.460784
HR           172150.574713
IT           172650.854545
Marketing    177127.200000
Sales        164615.216981
Name: Salary, dtype: float64

sort_values(by="Salary") → Sorts the DataFrame by the Salary column

ascending=False → Highest salary first.

head(5) → Returns the first 5 rows.

In [90]:
# Display the top 5 highest-paid employees
print(df.sort_values(by="Salary", ascending=False).head(5))

     Employee_ID  Age Department  Is_Manager Joining_Date  Experience  Salary  \
373         5076   63  Marketing        True   1988-09-25          36  293410
488         5175   64         IT       False   2001-10-01          35  285886
255         4801   62    Finance       False   2009-11-13          35  281861
118         4425   61         IT       False   1978-10-23          35  279946
202         1838   64         HR        True   2013-12-24          34  273400

        Bonus
373  49879.70
488  48600.62
255  47916.37
118  47590.82
202  46478.00

 Display the top  highest-paid employees

In [91]:
print(df.sort_values(by="Salary", ascending=False)m)

     Employee_ID  Age Department  Is_Manager Joining_Date  Experience  Salary  \
373         5076   63  Marketing        True   1988-09-25          36  293410
488         5175   64         IT       False   2001-10-01          35  285886
255         4801   62    Finance       False   2009-11-13          35  281861
118         4425   61         IT       False   1978-10-23          35  279946
202         1838   64         HR        True   2013-12-24          34  273400
..           ...  ...        ...         ...          ...         ...     ...
271         3881   23         IT        True   1972-02-07           9   67144
374         6914   23      Sales       False   2010-03-07           9   66124
405         9975   22         IT        True   2004-05-16           9   65079
186         7336   22      Sales        True   1995-04-25           8   57732
379         2974   22      Sales       False   2020-06-29           7   43177

        Bonus
373  49879.70
488  48600.62
255  47916.37
118  47590.82
202  46478.00
..        ...
271  11414.48
374  11241.08
405  11063.43
186   9814.44
379   7340.09

[500 rows x 8 columns]

True → Duplicate row

False → Unique row

In [98]:
print(df.duplicated()) #if any duplicate rows exist

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 500, dtype: bool

In [92]:
#Remove duplicate rows from the DataFrame
df.drop_duplicates()

# df.drop_duplicates(inplace=True)  --> here the inplace= True is for too modifie in the original dataframe

,Employee_ID,Age,Department,Is_Manager,Joining_Date,Experience,Salary,Bonus
0,8794,60,Finance,False,1994-03-24,30,238668,40573.56
1,8222,28,Sales,True,1979-12-08,13,105995,18019.15
2,7643,30,Marketing,False,1998-09-25,11,96120,16340.40
3,2737,38,HR,True,2011-11-23,20,153525,26099.25
4,8557,61,HR,True,1976-10-08,31,249192,42362.64
...,...,...,...,...,...,...,...,...
495,8426,32,Marketing,True,2013-12-04,16,126088,21434.96
496,9810,26,IT,True,2022-05-02,15,118094,20075.98
497,5396,34,Finance,False,2025-04-22,16,131208,22305.36
498,7546,60,HR,False,1970-01-13,28,224502,38165.34
499,7744,29,Finance,True,1988-06-21,15,114758,19508.86

In [95]:
# count the duplicate row
print(df.duplicated().sum())

0

In [96]:
print(df[df.duplicated()])

Empty DataFrame
Columns: [Employee_ID, Age, Department, Is_Manager, Joining_Date, Experience, Salary, Bonus]
Index: []

In [99]:
#duplicates based on a specific column
print(df["Department"].duplicated())

0      False
1      False
2      False
3      False
4       True
       ...
495     True
496     True
497     True
498     True
499     True
Name: Department, Length: 500, dtype: bool

In [100]:
#Count duplicate names:
print(df["Department"].duplicated().sum())

495

In [101]:
#Check duplicates based on multiple columns
print(df.duplicated(subset=["Experience", "Department"]))

0      False
1      False
2      False
3      False
4      False
       ...
495     True
496     True
497     True
498     True
499     True
Length: 500, dtype: bool

# ***Hard Level ***

 23. Merge two DataFrames employees and departments using the Department_ID column. 24. Create a pivot table showing the average salary of each department. 25. Find employees whose salary is greater than the average salary. 26. Remove outliers from the Salary column using the IQR method. 27. Convert the Joining_Date column to datetime format. 28. Create a new column Experience showing the number of years since each employee joined. 29. Save the cleaned DataFrame to a new CSV file named cleaned_data.csv. 30. Using only Pandas, create a report that includes: • Total employees  • Average salary  • Highest salary  • Lowest salary  • Employee count by department  • Employees with missing values  • Top 10 highest-paid employees

In [103]:
#Replace missing values in the Salary column with the column mean
df["Salary"].fillna(df["Salary"].mean(), inplace=True)

/tmp/ipykernel_2250/1333327931.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(df["Salary"].mean(), inplace=True)

In [104]:
df # as we saw there is no change in dataset

,Employee_ID,Age,Department,Is_Manager,Joining_Date,Experience,Salary,Bonus
0,8794,60,Finance,False,1994-03-24,30,238668,40573.56
1,8222,28,Sales,True,1979-12-08,13,105995,18019.15
2,7643,30,Marketing,False,1998-09-25,11,96120,16340.40
3,2737,38,HR,True,2011-11-23,20,153525,26099.25
4,8557,61,HR,True,1976-10-08,31,249192,42362.64
...,...,...,...,...,...,...,...,...
495,8426,32,Marketing,True,2013-12-04,16,126088,21434.96
496,9810,26,IT,True,2022-05-02,15,118094,20075.98
497,5396,34,Finance,False,2025-04-22,16,131208,22305.36
498,7546,60,HR,False,1970-01-13,28,224502,38165.34
499,7744,29,Finance,True,1988-06-21,15,114758,19508.86

In [106]:
#lets check is there is any null missing value is present?
df["Salary"].isnull().sum()

np.int64(0)

missing value in salary is not present ,that a reason when i apply the mean of the colm is not implement

In [107]:
#Replace missing values in the Department column with "Unknown"
df["Department"].fillna("Unknown", inplace=True)

/tmp/ipykernel_2250/3042676913.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Department"].fillna("Unknown", inplace=True)

In [108]:
df # as we saw there is no change in dataset bec there in no missinng value

,Employee_ID,Age,Department,Is_Manager,Joining_Date,Experience,Salary,Bonus
0,8794,60,Finance,False,1994-03-24,30,238668,40573.56
1,8222,28,Sales,True,1979-12-08,13,105995,18019.15
2,7643,30,Marketing,False,1998-09-25,11,96120,16340.40
3,2737,38,HR,True,2011-11-23,20,153525,26099.25
4,8557,61,HR,True,1976-10-08,31,249192,42362.64
...,...,...,...,...,...,...,...,...
495,8426,32,Marketing,True,2013-12-04,16,126088,21434.96
496,9810,26,IT,True,2022-05-02,15,118094,20075.98
497,5396,34,Finance,False,2025-04-22,16,131208,22305.36
498,7546,60,HR,False,1970-01-13,28,224502,38165.34
499,7744,29,Finance,True,1988-06-21,15,114758,19508.86

In [111]:
#now lets create 1st row with missing value then try to apply
new_row = pd.DataFrame({
    "Employee_ID": [9001],
    "Age": [30],
    "Department": None,
    "Is_Manager": [True],
    "Joining_Date": ["2024-01-15"],
    "Experience": [5],
    "Salary": [80000],
    "Bonus": [12000]
})

In [116]:
df = pd.concat([df, new_row], ignore_index=True) #pd.concat() → Joins DataFrames together
#ignore_index=True → Creates a new sequential index (0, 1, 2, ...)

In [115]:
df

,Employee_ID,Age,Department,Is_Manager,Joining_Date,Experience,Salary,Bonus
0,8794,60,Finance,False,1994-03-24,30,238668,40573.56
1,8222,28,Sales,True,1979-12-08,13,105995,18019.15
2,7643,30,Marketing,False,1998-09-25,11,96120,16340.40
3,2737,38,HR,True,2011-11-23,20,153525,26099.25
4,8557,61,HR,True,1976-10-08,31,249192,42362.64
...,...,...,...,...,...,...,...,...
496,9810,26,IT,True,2022-05-02,15,118094,20075.98
497,5396,34,Finance,False,2025-04-22,16,131208,22305.36
498,7546,60,HR,False,1970-01-13,28,224502,38165.34
499,7744,29,Finance,True,1988-06-21,15,114758,19508.86
500,9001,30,None,True,2024-01-15,5,80000,12000.00

In [117]:
df["Department"].fillna("Unknown", inplace=True)

/tmp/ipykernel_2250/1524427845.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Department"].fillna("Unknown", inplace=True)

In [118]:
df

,Employee_ID,Age,Department,Is_Manager,Joining_Date,Experience,Salary,Bonus
0,8794,60,Finance,False,1994-03-24,30,238668,40573.56
1,8222,28,Sales,True,1979-12-08,13,105995,18019.15
2,7643,30,Marketing,False,1998-09-25,11,96120,16340.40
3,2737,38,HR,True,2011-11-23,20,153525,26099.25
4,8557,61,HR,True,1976-10-08,31,249192,42362.64
...,...,...,...,...,...,...,...,...
497,5396,34,Finance,False,2025-04-22,16,131208,22305.36
498,7546,60,HR,False,1970-01-13,28,224502,38165.34
499,7744,29,Finance,True,1988-06-21,15,114758,19508.86
500,9001,30,Unknown,True,2024-01-15,5,80000,12000.00
501,9001,30,Unknown,True,2024-01-15,5,80000,12000.00